In [1]:
import numpy as np

## 1. Why is python numpy better than lists?

Numpy arrays are faster, consume less memory and have more functionality

## 2. Describe Python map function

Map executes as 1) argument on all of the elements of the iteratble 2) given as the second argument

In [10]:
# Return double of n 
def addition(n): 
    return n + n 
  
# We double all numbers using map() 
numbers = (1, 2, 3, 4) 
result = map(addition, numbers) 
print(list(result))

[2, 4, 6, 8]


## 3. Generate the array of 100 random numbers samplefrom a std normal distribution

In [3]:
data = np.random.rand(100);
data[:10]

array([0.08934179, 0.4816048 , 0.64627638, 0.55626814, 0.90944231,
       0.62404554, 0.37992254, 0.02555023, 0.85314339, 0.35895992])

## 4. How to count the occurrence of each value in a numpy array?

In [5]:
arr = np.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 9, 9])
#bincount is only valid for positive integers
np.bincount(arr)

array([4, 1, 1, 1, 2, 3, 0, 0, 0, 2])

## 5. Does numpy support Nan?

In [ ]:
Yes

## 6. What does the ravel() function in numpy do?

combines multiple numpy arrays into a single array

## 7. What is the meaning of axis =0 and axis =1?

Axis = 0 is meant for reading rows and axis = 1 is meant for reading columns

## 8. What is numpy and describe its use cases?

Numpy is a package that supports large multidimensional arrays and matrices along with a large collection of high level mathematical functions. It is an optimized version of python lists like financial functions, linear algebra, statistics, polynomicals, sorting and searching.

## 9. How do you remove from one array those items that exist in another array?

In [7]:
arr = np.array([5,4,3,2,1])
brr = np.array([4,8,9,10,1])
#to remove from a all of b

np.setdiff1d(arr, brr)

array([2, 3, 5])

## 10. How to sort a numpy array by a specific column - say column 2

## Use the syntax array[:, j - 1] to extract the j-th column of an array. Call numpy.argsort(a) to return the sorted indices of the column a. Then use these sorted indices to sort the rows of the same array by column a.

In [19]:
arr = np.array([[1, 2, 3],[4, 5, 6],[0, 0, 1]])
#np.argsort() returns the indicies of the original item
#if it were to be in a sorted array

arr


array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 1]])

## so here get indicies sorted of col 2, which is


In [17]:
np.argsort(arr[:,1])

array([2, 0, 1])

In [18]:
arr[arr[:,1].argsort()]

array([[0, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])

## 11. how to reverse a numpy array most efficiently?

In [21]:
arr = np.array([9, 10, 1, 2, 0]);
arr


array([ 9, 10,  1,  2,  0])

In [22]:
arr[::-1]

array([ 0,  2,  1, 10,  9])

## 12. Calculate percentiles using numpy

In [23]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]);
arr

array([11, 22, 33, 44, 55, 66, 77])

In [24]:
per = np.percentile(arr, 40);
per

37.400000000000006

## 13. What is the difference between numpy and scipy?

numpy would contain nothing but the array data type and the most basic operations like 
- indexing
- sorting
- reshaping
- basic element wise functions

all numerical code would reside in scipy
which contains more fully featured versions fo the linear algebra models as well as other numerical algos

## 14. What is the preferred way to check for an empty element array?

Size attribute is helpful for determining length of array

In [29]:
arr = np.zeros((3,4));
arr.size

12

## 15. What is the difference between Matricies and Arrays?

Matricies can only be 2 dimensionsal where arrays can have any number of dimensions

## 16. How can you find the indicies of an array where a condition is true?

In [30]:
arr = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]]);
arr

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [31]:
arr[arr > 3]

array([9, 8, 7, 6, 5, 4])

In [32]:
arr > 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

## 17. find min and max of flattened array?

In [34]:
arr = np.arange(4).reshape(2,2);
arr

array([[0, 1],
       [2, 3]])

In [36]:
maximum = np.amax(arr)
minimum = np.amin(arr);
maximum, minimum 

(3, 0)

## 18. Write numpy to calc difference between min and max values of array along second axis

In [39]:
arr = np.arange(16).reshape(4,4);
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
res = np.ptp(arr,1);
res

array([3, 3, 3, 3])

## 19. find the median of an array

In [44]:
arr = np.arange(16).reshape(4,4);
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
res = np.median(arr);
res

7.5

## 20. mean, std dev and variance of array on the 2nd axis


In [49]:
arr = np.arange(16).reshape(16,);
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
mean = np.mean(arr)
std = np.std(arr)
var = np.var(arr);
mean, std, var

(7.5, 4.6097722286464435, 21.25)

## 21. calculate covariance matrix between 2 arrays

In [ ]:
a = np.array([0,1,3])
b = np.array([2,4,5])

covariance_matrix = 